# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    defaults:
      run:
        shell: msys2 {0}
    steps:

      - name: test windows
        run: |
          dir C:\ProgramData\Chocolatey
          dir C:\ProgramData\Chocolatey\bin
          dir C:\
          dir "C:\Program Files"
          dir "C:\Program Files (x86)"
          dir "C:\Msys2"
      # Setup build functions
      #- name: Set up MinGW
      #  uses: egor-tensin/setup-mingw@v2
      - name: Install Tools
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install rsync make mingw
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: make release
